import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Landing Page Templates",
  description: "Generated by create next app",
};

export default function LPTemplatesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1>Landing Page Templates</h1>
          {children}
      </body>
    </html>
  );
}
